### ISSUE TITLE
発表評価シート作成

### ISSUE THREAD

**Issue by kalupas226** [2017pro02/Jinkawa#30]
- おそらくTeXで作成する必要あり

- 7月7日（金）19:00まで提出

- 関連リンク：[発表評価シート概要](http://sisp.fun.ac.jp/moodle/mod/assignment/view.php?id=1224),[pdfファイル](http://sisp.fun.ac.jp/HPJver2.0/4.TasksOfStudents/evalsheet00.pdf),[TeXファイル](http://sisp.fun.ac.jp/HPJver2.0/4.TasksOfStudents/evalsheet00.tex)

**Comment by ysnkw21** [comment]
作成完了したためclosesします
